config/routes.rb
Rails.application.routes.draw do
  root 'graphs#new'

  resources :users, except: [:index, :edit, :update]
  
  get 'sessions/new' => 'sessions#new', as: 'login'
  post 'sessions'    => 'sessions#create'
  delete 'sessions'  => 'sessions#destroy'

  get 'graphs/new' => 'graphs#new' # html
  get 'graphs' => 'graphs#index' # api
  post 'graphs' => 'graphs#create' # api
  get 'graphs/:id' => 'graphs#read'
  delete 'graphs/:id' => 'graphs#destroy'
  put 'graphs/:id' => 'graphs#update'

  get 'graphs/show/:id' => 'graphs#show'
  get 'graphs/edit/:id' => 'graphs#edit'

  get 'graphs/editinfo/:id' => 'graphs#edit_info'

end

app/models/color.rb
class Color < ActiveRecord::Base
	has_and_belongs_to_many :graphs

	validates_presence_of :hexadecimal
end

app/models/graph.rb
class Graph < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :colors

	validates_presence_of :name
	validates_presence_of :category
	# validates :difficulty, numericality: { only_integer: true }
	# validates :gauge, numericality: { only_integer: true }
	# validates :rows, presence: true, numericality: { only_integer: true }
	# validates :columns, presence: true, numericality: { only_integer: true }
	# validates :number_of_colors, presence: true, numericality: { only_integer: true }
	validates :layout, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :graphs, dependent: :destroy

	validates :username, presence: true, uniqueness: true
	validates_presence_of :first_name
	validates_presence_of :last_name

	validates :email, presence: true, uniqueness: true, confirmation: true
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  	render layout: 'application', text: ''
  end

  helper_method :current_user

  def authenticate
    redirect_to login_path unless session[:current_user_id]
  end

  def current_user
   	User.find(session[:current_user_id]) if session[:current_user_id]
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  def index
    @graphs = Graph.all
  end

  def show
    @graph = Graph.find(params[:id])
  end

  def read
    render json: Graph.find(params[:id])
  end

  def edit
    @graph = Graph.find(params[:id])
    @colors = Color.all
    puts "************* EDIT **************"
    render :new
  end

  def new
    @colors = Color.all
    @graph = Graph.new
  end

  def create
    g = Graph.create(graph_params)
    g.update(user_id: current_user.id)
    render json: g
  end

  def update
    render json: Graph.update(params[:id], graph_params)
  end

  def destroy
    @graph = Graph.find(params[:id])
    @graph.destroy
    # You can't do this because backbone is calling destroy,
    # and it must get a json as a response
    # redirect_to graphs_new_path
    render json: {success: true}
  end

  private

  def graph_params
    params.require(:graph).permit(:user_id, :name, :category, :image_url, :product_image, :layout, :notes, :privacy, :preview)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		if session[:current_user_id]
			redirect_to graphs_new_path
		end
	end

	def create
		@user = User.find_by(username: params[:username])
		if @user && @user.authenticate(params[:password])
			session[:current_user_id] = @user.id
			redirect_to graphs_new_path
		else
			flash[:login_error] = "That username password combo does not match our records. Please try again, sign-up, or continue as guest."
			render :new
		end
	end

	def destroy
		session[:current_user_id] = nil
		flash[:logout] = "You have successfully logged out"
		redirect_to graphs_new_path
	end
	
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def index
		render json: User.all
	end

	def show
		render json: User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		render json: User.create(user_params)
	end

	def edit
		# check to see if this section is correct
		if current_user
			render json: User.find(params[:id])
		end
	end

	def update
		render json: User.update(params[:id], user_params)
	end

	def destroy
		render json: User.destroy(params[:id])
	end

	private

	def user_params
		params.require(:user).permit(:username, :first_name, :last_name, :email, :password_digest)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		# @current_user = current_user
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user_id = session[:current_user_id]
		if @user.save
			session[:current_user_id] = @user.id
			redirect_to @user
		else
			render :new
		end
	end

	def destroy
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to users_path
		else
			@user.destroy
			session[:current_user_id] = nil
			redirect_to graphs_path
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/graphs/_form.html.erb
<!-- this form will be used to alter the graph information-->
<%= form_for @graph do |f| %>
  <div class="input">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="input">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="input">
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </div>
  
  <div class="input" id="delete">
    <%= link_to "Delete Graph", graphs_path(@graph), method: :delete %>
  </div>

  <%= f.submit "Submit", :id=>"submit" %>
<% end %>

app/views/graphs/edit_info.html.erb
<div class="form" id="signup">
	<div>
		<h1>Edit Your Graph's Information</h1>
		<% if @user.errors.any? %>
		    <h3 style="color:#fa4f20">Please fix the appropriate fields:</h3>
		<% end %>
		<%= render 'form' %>
	</div>
</div>

app/views/graphs/index.html.erb
<script>
	$('#all').css({'border-radius':'5px', 'border':'2.5px solid #f36d74', 'color':'white'});
</script>

<div class='container' id='graphs-index'>
	<h1>All Public Graphs</h1><br>
	<% @graphs.each do |graph| %>
		<a href="/graphs/show/<%= graph.id %>">
			<img class="thumbnail" src="<%= graph.preview %>" style="max-width: 155px;">
		</a>
	<% end %>
</div>

app/views/graphs/new.html.erb
<script>
	$('#new').css({'border-radius':'5px', 'border':'2.5px solid #fd724c', 'padding':'5px', 'color':'white'}); 
		</script>

<div class='container' id='graphs-new' <% if session[:current_user_id] %>data-userid='<%= current_user.id %>'<% end %>>

	<div id='graph-buttons-container'>
		<% if session[:current_user_id] %>
			<div id="actions">
				<a class='button' id="saveGraph">Save</a>
				<a class='button' id="downloadLnk" download="MyGraph.jpg">Download Graph</a>
				<a class='button' id="deleteGraph" >Delete</a>
			</div>
		<% else %>
			<div id="actions">
				<a class='button' id="downloadLnk" download="MyGraph.jpg">Download Graph</a>
			</div>
		<% end %>
		<div style='display: inline-block;'>
			<h3 id='swatch-head'>Swatches</h3>
			<div id="color-palette">
				<% @colors.each do |color| %>
					<div class="swatch" id="<%= color.hexadecimal %>" onClick="setCurrentColor('<%= color.hexadecimal %>')" style="background-color: <%= color.hexadecimal %> " >
					</div>
				<% end %>
			</div>
		</div>

		<div id='graph-container'>
			<h3 id='graph-title'></h3>
			<canvas id="graph" width="800" height="800"></canvas>
			<!-- <canvas id="graph" width="1400" height="740"></canvas> -->
		</div>
	</div>
	<div id="graphInfo-container"></div>
	<div id="preview"></div>
</div>

<% if !params[:id].nil? %>
	<script>
	  console.log("Hello, loading " + <%= params[:id] %>);
	  //loadGraph(<%= params[:id] %>);

	  graphModel = new Graph;
	  graphModel.id = <%= @graph.id %>;
	  graphModel.name = '<%= @graph.name %>';
	  graphModel.category = '<%= @graph.category %>';
	  graphModel.layout = '<%= @graph.layout %>';
	  graphModel.privacy = <%= @graph.privacy %>;
	  graphModel.drawGraphTemplate();
	  graphModel.redraw();
	</script>
<% else %>
  <script>console.log("PARAMS ID IS NUL");</script>
<% end %>

app/views/graphs/show.html.erb
<div class='container' id='show-graph' data-graphid='<%= @graph.id %>'>
	<div id='graph-buttons-container'>
<!-- 		<div id="actions">
			<a class='button' id="downloadLnk" download="MyGraph.jpg">Download Graph</a>
		</div> -->
		
		<div id='graph-container'>
			<h3 id='graph-title'></h3>
			<canvas id="graph" width="800" height="800"></canvas>
		</div>
	</div>
</div>

<% if !params[:id].nil? %>
	<script>
	  console.log("Hello, loading " + <%= params[:id] %>);
	  //loadGraph(<%= params[:id] %>);

	  graphModel = new Graph;
	  graphModel.id = <%= @graph.id %>;
	  graphModel.name = '<%= @graph.name %>';
	  graphModel.category = '<%= @graph.category %>';
	  graphModel.layout = '<%= @graph.layout %>';
	  graphModel.privacy = <%= @graph.privacy %>;
	  graphModel.drawGraphTemplate();
	  graphModel.redraw();
	</script>
<% else %>
  <script>console.log("PARAMS ID IS NUL");</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GraphKnitApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id='logo-container'>
	<%= link_to graphs_new_path, method: :get do %>
		<img src='http://i.imgur.com/KuFBt6b.png' style='height: 45px; margin-top: 18px;'>
	<% end %>
</div>

<ul id="navbar">
	<li id='link-block'>
		<% if session[:current_user_id] %>
			<%= render partial: 'navbar/navbar', locals: { navbar: [:welcome, :profile, :graphs, :newGraph] } %>
		<% else %>
			<%= render partial: 'navbar/navbar', locals: { navbar: [:log_in, :sign_up] } %>
		<% end %>
	</li>
</ul>

	<%= yield %>
</body>
</html>

app/views/navbar/_navbar.html.erb
<% if navbar.include? (:profile) %>
	<li>
		<div class="divider" style="background: #ab47c4;"></div>
	</li>

	<li class="nav_link" id="my">
		<%= link_to "My Graphs", user_path(current_user) %>
	</li>
	
	<li>
		<div class="divider" style="background: #f36d74;"></div>
	</li>
<% end %>

<% if navbar.include? (:graphs) %>
	<li class="nav_link" id="all">
		<%= link_to "All Graphs", graphs_path %>
	</li>
	
	<li>
		<div class="divider" style="background: #fd724c;"></div>
	</li>
<% end %>

<% if navbar.include? (:newGraph) %>
	<li class="nav_link" id="new">
		<%= link_to "New Graph", graphs_new_path, method: :get %>
	</li>

	<li>
		<div class="divider" style="background: #ffe578;"></div>
	</li>
<% end %>


<div style="float: right; margin: -57px; margin-right: 0; color: white;">
	<% if navbar.include? (:welcome) %>
		<li class="nav_link" id="profile">
			<span>Welcome <%= current_user.username %></span><li style='margin: 0 3px;'>|</li>
		</li>
		<li id='logout' style='padding-right: 10px;'><%= link_to "Log Out", sessions_path, method: :delete %>
		</li>
	<% end %>

	<% if navbar.include? (:sign_up) %>
		<li class="nav_link">
			<%= link_to "Sign Up", new_user_path %>
		</li>
			
		<li>
			<div class="divider" style="background: #fec538;"></div>
		</li>
	<% end %>

	<% if navbar.include? (:log_in) %>
		<li class="nav_link">
			<%= link_to "Log In", login_path %>
		</li>
	<% end %>
</div>

app/views/users/_form.html.erb
<!-- this form will be used to add a new user and to edit an existing user -->
<%= form_for (@user), :validate => true do |f| %>
  <div class="input">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="input">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  
  <div class="input">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="input" id='email'>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= text_field :person, :email_confirmation %>
  </div>

  <div class="input">
    <%= f.label :password %>
    <%= f.password_field :password %>
 </div>
  
  <div class="input">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit "Submit", :id=>"submit" %>
 
  <span id="cancel">
    <% if session[:current_user_id] %>
      <%= link_to "Cancel", user_path(@user) %>  | 
    <% end %>
    <% if delete %>
      <%= link_to "Delete User", user_path(@user), method: :delete %>
    <% end %>
  </span>
<% end %>

app/views/users/new.html.erb
<div class="form" id="signup">
	<div>
		<h1>Join the Community!</h1>
		<% if @user.errors.any? %>
		    <h3 style="color:#fa4f20">Please fix the appropriate fields:</h3>
		<% end %>
		<%= render partial: 'form', locals: { new_user: true, delete: false, edit: false } %>
	</div>
</div>

app/views/users/show.html.erb
<script>
	$('#my').css({'border-radius':'5px', 'border':'2.5px solid #ab47c4', 'color':'white'});
</script>

<div class='container' id='my-graphs'>
	<h1>My Graphs</h1><br>
	<h2>Click Graph to Edit</h2><br>
	<% @user.graphs.each do |image| %>
		<a href="/graphs/edit/<%= image.id %>">
			<img class="thumbnail" src="<%= image.preview %>" style="max-width: 155px;">
		</a>
	<% end %>
</div>